name: Web E2E tests
on: 
  workflow_dispatch:

  jobs:
    web-tests:

    runs-on: ubuntu-latest

    steps:
    # Clone do projeto
      - uses: actions/checkout@v4
    # Conferir a versão do Node
      - name: Node versionSpec
        run: node node--version

      - name: Instalando dependencias
        run: npm install

      - name: Executando testes
        run: npx cypress-run